JavaScript/FunctionalJavaScript/Asynchronous/README.md
JavaScript/FunctionalJavaScript/Asynchronous/lazyConcurrency.js
JavaScript/FunctionalJavaScript/rx/index.js

- 게으른 함수들을 빠르게 계산하기 위해 동시 평가가 가능한 reduce, take 구현법에 대해 학습함

게으른 함수들을 병렬적으로 처리하기

---

JavaScript/FunctionalJavaScript/Asynchronous/README.md
JavaScript/FunctionalJavaScript/Asynchronous/allCompositionExample.js
JavaScript/FunctionalJavaScript/Asynchronous/concurrentMapFilterExample.js
JavaScript/FunctionalJavaScript/rx/index.js

- C.takeAll 함수 작성
- C.map, C.filter 함수 작성
- 이 함수들을 통해 여러 함수 중 특정 함수만 병렬적으로 평가가 가능함

즉시 병렬적으로 평가하기

---

JavaScript/FunctionalJavaScript/rx/index.js

- 기존 코드에서 필요없는 변수 선언 제거
- 좀 더 명확한 표현으로 변경

C.reduce 리팩토링

---

JavaScript/FunctionalJavaScript/Asynchronous/README.md
JavaScript/FunctionalJavaScript/Asynchronous/asyncAwait.js

- 결국 Promise 기반이다.
- 혼용해서 사용할 때는 서로의 차이점에 대해 명확히 인식하고 사용해라

Async/Await의 주의 사항

---

Java/effectiveJava/README.md
Java/effectiveJava/src/main/java/com/poppo/effective/item7/MemoryLeakStack.java
JavaScript/FunctionalJavaScript/FrequentlyQna/README.md
JavaScript/FunctionalJavaScript/FrequentlyQna/pipelineWithAsyncAwait.js
JavaScript/FunctionalJavaScript/FrequentlyQna/whyFxjs.js
JavaScript/FunctionalJavaScript/FrequentlyQna/whyPipeline.js

- 자바에서도 메모리 관리가 왜 필요한지, 언제 하는지, 어떻게 하는지에 대해 배웠습니다.
- 자바스크립트 array 프로토타입에서 제공하는 map, reduce, filter 등 외에 FxJS를 사용하는 이유에 대해 배웠습니다.
- async/await가 있어도 파이프라인 함수가 왜 필요하며 둘의 목적이 어떻게 다른지에 대해 배웠습니다.
- async/await와 파이프라인을 섞어서 사용하는 이유에 대해 배웠습니다.

왜 array 프로토타입의 map 대신 FxJS인가?

---

JavaScript/FunctionalJavaScriptAdvanced/changeToFunctional/README.md
JavaScript/FunctionalJavaScriptAdvanced/changeToFunctional/queryExample.js
JavaScript/FunctionalJavaScriptAdvanced/changeToFunctional/userExample.js

- reduce 과다 사용을 줄여서 명령형 습관을 벗어나는 연습

reduce의 보조함수를 가볍게 만들기 실습

---

JavaScript/FunctionalJavaScriptAdvanced/changeToFunctional/README.md
JavaScript/FunctionalJavaScriptAdvanced/changeToFunctional/queryToObj.js
JavaScript/FunctionalJavaScriptAdvanced/safeFunctionComposition/README.md
JavaScript/FunctionalJavaScriptAdvanced/safeFunctionComposition/safeComposition.js
JavaScript/FunctionalJavaScriptAdvanced/safeFunctionComposition/useFilter.js

- reduce의 보조함수 작게 가져가기 연습
- 배열 모나드와 지연 평가 filter, take를 활용한 안전한 함수 합성

20200210til

---

JavaScript/FunctionalJavaScriptAdvanced/objectToIterable/README.md
JavaScript/FunctionalJavaScriptAdvanced/objectToIterable/valuesExample.js

- 여기서 객체는 자바스크립트 객체 타입(키, 값 쌍)을 기준으로 학습한다.
- L.value 함수를 통해 지연적으로 객체 값 이터러블을 다룰 수 있도록 한다

객체를 이터러블로 다루기

---

Spring/Java/springbootMsaExample/currency-conversion-service/acceptanceTest/tcp8100.http
Spring/Java/springbootMsaExample/currency-conversion-service/pom.xml
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/CurrencyConversionServiceApplication.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/applications/CurrencyExchangeServiceProxy.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/applications/RestTemplateService.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/config/JWTTokenEnhancer.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/config/JWTTokenStoreConfig.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/config/ServiceConfig.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/controller/CurrencyConversionController.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/filter/UserContextFilter.java
Spring/Java/springbootMsaExample/currency-conversion-service/src/main/java/com/poppo/spring/cloud/microservices/currencyconversionservice/security/UserContextInterceptor.java
Spring/Java/springbootMsaExample/currency-exchange-service/acceptanceTest/exchange8000.http
Spring/Java/springbootMsaExample/currency-exchange-service/pom.xml
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/CurrencyExchangeServiceApplication.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/config/JWTTokenEnhancer.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/config/JWTTokenStoreConfig.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/config/ServiceConfig.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/filter/UserContext.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/filter/UserContextFilter.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/filter/UserContextHolder.java
Spring/Java/springbootMsaExample/currency-exchange-service/src/main/java/com/poppo/spring/cloud/microservices/currencyexchangeservice/security/ResourceServerConfiguration.java
Spring/Java/springbootMsaExample/netflix-eureka-naming-server/pom.xml
Spring/Java/springbootMsaExample/spring-cloud-security/pom.xml
Spring/Java/springbootMsaExample/spring-cloud-security/src/main/java/com/poppo/spring/cloud/security/config/CustomAccessTokenConverter.java
Spring/Java/springbootMsaExample/spring-cloud-security/src/main/java/com/poppo/spring/cloud/security/config/JWTOAuth2Config.java
Spring/Java/springbootMsaExample/spring-cloud-security/src/main/java/com/poppo/spring/cloud/security/config/JWTTokenEnhancer.java
Spring/Java/springbootMsaExample/spring-cloud-security/src/main/java/com/poppo/spring/cloud/security/config/JWTTokenStoreConfig.java
Spring/Java/springbootMsaExample/spring-cloud-security/src/main/java/com/poppo/spring/cloud/security/config/ServiceConfig.java

- 뭔가 찜찜하게 구성됨
- 아직 어떻게 돌아가는지 잘 모르겠음

스프링 클라우드 OAuth+JWT 구성

---

JavaScript/FunctionalJavaScriptAdvanced/.idea/.gitignore
JavaScript/FunctionalJavaScriptAdvanced/.idea/FunctionalJavaScriptAdvanced.iml
JavaScript/FunctionalJavaScriptAdvanced/.idea/misc.xml
JavaScript/FunctionalJavaScriptAdvanced/.idea/modules.xml
JavaScript/FunctionalJavaScriptAdvanced/.idea/vcs.xml
JavaScript/FunctionalJavaScriptAdvanced/objectToIterable/README.md
JavaScript/FunctionalJavaScriptAdvanced/objectToIterable/indexByExample.js
JavaScript/FunctionalJavaScriptAdvanced/objectToIterable/pickExample.js
JavaScript/FunctionalJavaScriptAdvanced/userDefinedObject/README.md
JavaScript/FunctionalJavaScriptAdvanced/userDefinedObject/mapSetExample.js
JavaScript/FunctionalJavaScriptAdvanced/userDefinedObject/modelCollectionExample.js
JavaScript/FunctionalJavaScriptAdvanced/userDefinedObject/productProductsExample.js

- 사용자 정의 객체를 이터러블로 다루는 방법에 대해 학습했습니다.
- 자바스크립트 기본객체 Map, Set을 통한 준비운동
- 실제 사용자 정의 객체를 만들고 배운 개념 적용해보기

20200219til

---

JavaScript/fpPractise/.idea/.gitignore
JavaScript/fpPractise/.idea/dictionaries/saul.xml
JavaScript/fpPractise/.idea/fpPractise.iml
JavaScript/fpPractise/.idea/misc.xml
JavaScript/fpPractise/.idea/modules.xml
JavaScript/fpPractise/.idea/vcs.xml
JavaScript/fpPractise/inflearnPractise/schedulerExample.js

- 오늘은 부모님 이사 돕느라 너무 힘들어서 이것만..

함수형 실습1 - 아임포트 스케줄러 작성

---

JavaScript/fpPractise/inflearnPractise/frontendExample.html

20200309til

---

android/practise/README2.md
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/fragment/Fragment1.kt
android/practise/app/src/main/java/com/poppo/practise/fragment/FragmentActivity.kt
android/practise/app/src/main/res/layout/activity_fragment.xml
android/practise/app/src/main/res/layout/fragment_one.xml

- Fragment 개념 학습 및 실습
- null safety의 정의와 필요성

20200401til

---

android/practise/README2.md
android/practise/app/build.gradle
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/AddViewActivityPrac.kt
android/practise/app/src/main/java/com/poppo/practise/LibraryPractise.kt
android/practise/app/src/main/java/com/poppo/practise/NullSafety.kt
android/practise/app/src/main/java/com/poppo/practise/Resource.kt
android/practise/app/src/main/java/com/poppo/practise/ThreadPractise.kt
android/practise/app/src/main/res/layout/activity_add_view_prac.xml
android/practise/app/src/main/res/layout/activity_library_practise.xml
android/practise/app/src/main/res/layout/activity_null_safety.xml
android/practise/app/src/main/res/layout/activity_resource.xml
android/practise/app/src/main/res/layout/activity_thread_practise.xml
android/practise/app/src/main/res/layout/item_view.xml
android/practise/app/src/main/res/layout/resource_example.xml
android/practise/app/src/main/res/values/colors.xml
android/practise/app/src/main/res/values/strings.xml
android/practise/app/src/main/res/values/styles.xml
android/practise/build.gradle

- List View 개념 학습
- AddView를 통한 List View 그리기 개념 학습

20200402til

---

android/practise/README2.md
android/practise/app/build.gradle
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/RecyclerViewActivity.kt
android/practise/app/src/main/res/layout/activity_recycler_view.xml
android/practise/app/src/main/res/layout/item_view.xml

20200406til

---

android/practise/.idea/misc.xml
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/RecyclerViewActivity.kt
android/practise/app/src/main/java/com/poppo/practise/RecyclerViewPhoneBook.kt
android/practise/app/src/main/res/layout/activity_recycler_view_phone_book.xml
android/practise/app/src/main/res/layout/item_view.xml

안드로이드 개발 학습

---

android/practise/.idea/misc.xml
android/practise/README2.md
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/RecyclerViewPhoneBook.kt
ethereum/smartContractPrac/trufflePrac/.gitignore 3

- RecyclerView 실습 마무리
- RecyclerView에서 Intent 실행하기 실습
- Pager, TabLayout 개념 학습

20200408til

---

android/practise/README2.md
android/practise/app/build.gradle
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/RealmActivity.kt
android/practise/app/src/main/java/com/poppo/practise/School.kt
android/practise/app/src/main/java/com/poppo/practise/SharedPreferenceActivity.kt
android/practise/app/src/main/java/com/poppo/practise/TabPager2Activity.kt
android/practise/app/src/main/java/com/poppo/practise/TabPagerActivity.kt
android/practise/app/src/main/java/com/poppo/practise/fragment/Fragment2.kt
android/practise/app/src/main/java/com/poppo/practise/fragment/Fragment3.kt
android/practise/app/src/main/java/com/poppo/practise/fragment/Fragment4.kt
android/practise/app/src/main/res/layout/activity_realm.xml
android/practise/app/src/main/res/layout/activity_shared_preference.xml
android/practise/app/src/main/res/layout/activity_tab_pager2.xml
android/practise/app/src/main/res/layout/fragment_four.xml
android/practise/app/src/main/res/layout/fragment_three.xml
android/practise/app/src/main/res/layout/fragment_two.xml
android/practise/build.gradle

- 안드로이드 DB 학습
- Realm 개념 학습 및 실습
- SharedPreference 개념 학습 및 실습

20200410til

---

android/practise/README2.md
android/practise/app/src/main/AndroidManifest.xml
android/practise/app/src/main/java/com/poppo/practise/AsyncActivity.kt
android/practise/app/src/main/res/layout/activity_async.xml

안드로이드 기초 학습

---

kubernetes/RollingUpdateAndRollback/README.md
kubernetes/RollingUpdateAndRollback/http-go-deploy-v1.yaml
kubernetes/yaml/alpine-deploy.yaml
kubernetes/yaml/alpine-deployment.yaml
kubernetes/yaml/http-go-deploy-v1.yaml
kubernetes/yaml/ns-deployment-jenkins.yaml
kubernetes/yaml/ns-jenkins.yaml

쿠버네티스 학습
- 네임스페이스 학습
- 롤링업데이트, 롤백 학습

20200419til

---

Java/effectiveJava/README2.md
Java/effectiveJava/src/main/java/com/poppo/effective/item13/PhoneNumber.java
kubernetes/Service/README.md
kubernetes/Service/http-go-ingress.yaml
kubernetes/Service/http-go-lb.yaml
kubernetes/Service/tomcat-deploy.yaml
kubernetes/Service/tomcat-ingress.yaml
kubernetes/Service/tomcat-np.yaml
kubernetes/Service/tomcat-sample.yaml

- 자바에서 Comparable 인터페이스 구현을 고려해야하는 이유
-  쿠버네티스 서비스 개념 학습 및 실습
- 노드포트, 로드밸런서, 인그레스

20200421til

---

React/mashup-todolist/src/App.js
React/mashup-todolist/src/Components/TodoContext.js
React/mashup-todolist/src/Components/TodoCreate.js
React/mashup-todolist/src/Components/TodoHead.js
React/mashup-todolist/src/Components/TodoItem.js
React/mashup-todolist/src/Components/TodoList.js

- 할일 추가 버튼 스타일링 및 구현
- 할일 추가 버튼 컴포넌트 구현
- 클릭 시 변화 이벤트 추가
- 클릭 시 input 컴포넌트 보여주도록 변경
- Reducer 개발
- 할일 context 개발
- Todo 헤드 기능 구현
- JS를 이용한 날짜 및 요일 표기
- Context를 이용한 남은 할일 목록 갯수 구하기
- Context를 이용해서 할일 목록 표기
- TodoItem에서 한일 목록 표기 구현
- 휴지통 클릭 시 삭제 기능 구현
- dispatch 활용
- 새로운 할일 추가하기 기능 구현

20200509til

---

Spring/Java/queryDsl/src/main/java/com/poppo/spring/jpa/entity/Member.java
Spring/Java/queryDsl/src/main/resources/application.yml
Spring/Java/queryDsl/src/test/java/com/poppo/spring/jpa/QueryDslBasicTests.java

- 정렬 방법 학습
- 롬복은 똑바로 알고 쓰자 잘못 쓰면 객체 꼬인다

QueryDSL 학습

---

Spring/Java/queryDsl/src/test/java/com/poppo/spring/jpa/QueryDslBasicTests.java

20200513til

---

Frontend/HtmlAndCss/CssFlexGrid/README.md
Frontend/HtmlAndCss/CssFlexGrid/flexbox/index.html
Frontend/HtmlAndCss/CssFlexGrid/flexbox/styles.css
Frontend/HtmlAndCss/InteractiveWeb/blank.html
Frontend/HtmlAndCss/InteractiveWeb/css/default.css
Frontend/HtmlAndCss/InteractiveWeb/css/main.css
Frontend/HtmlAndCss/InteractiveWeb/index.html

20200721til

---

Frontend/HtmlAndCss/InteractiveWeb/css/main.css
Frontend/HtmlAndCss/InteractiveWeb/js/main.js

feat(blendImage): reveal by scroll position
